name: Tag

on:
  push:
    branches: [master]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: fetch all tags and histories
        run: git fetch --unshallow --tags

      - name: setup user name and email
        run: |
          git config --global user.email "xordog@gmail.com"
          git config --global user.name "xord"

      - name: ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: install xot gem
        run: gem install xot

      - name: tag versions
        run: rake tag:versions

      - name: push tags
        run: git push origin --tags
